
//general
export const IS_LOADING = "IS_LOADING";
export const SET_CODE = "SET_CODE";
export const SET_ERROR = "SET_ERROR";
export const SET_REQUEST_OTP_STATUS = "SET_REQUEST_OTP_STATUS";
export const NEXT_STEP = "NEXT_STEP";
export const PREVIOUS_STEP = "PREVIOUS_STEP";
export const RESET_STEP = "RESET_STEP";
export const SET_STEP = "SET_STEP";
export const SET_GENERAL_DATA = "SET_GENERAL_DATA";
export const RESET_GENERAL_DATA = "RESET_GENERAL_DATA";
export const SET_VERIFY_CODE_FAILURE_DIALOG = "SET_VERIFY_CODE_FAILURE_DIALOG";
export const SET_REFERENCE_IMG = "SET_REFERENCE_IMG";

export const SET_ENCODE_URI_BK = "SET_ENCODE_URI_BK";

//financial
export const SET_FINANCING_FORM_DATA = "SET_FINANCING_FORM_DATA";
export const RESET_FINANCING_FORM_DATA = "RESET_FINANCING_FORM_DATA";
export const SET_FINANCING_AMOUNT = "SET_FINANCING_AMOUNT";
export const SET_DURATION = "SET_DURATION";
export const SET_TENURE = "SET_TENURE";
export const SET_AGREEMENT_1 = "SET_AGREEMENT_1";
export const SET_AGREEMENT_2 = "SET_AGREEMENT_2";
export const SET_AGREEMENT_3 = "SET_AGREEMENT_3";

// business
export const SET_BUSINESS_FORM_DATA = "SET_BUSINESS_FORM_DATA";
export const RESET_BUSINESS_FORM_DATA = "RESET_BUSINESS_FORM_DATA";
export const SET_STORE_IMAGE_URL ="SET_STORE_IMAGE_URL";
export const SET_SSM_IMAGE_URL = "SET_SSM_IMAGE_URL";

// Personal
export const SET_PERSONAL_FORM_DATA = "SET_PERSONAL_FORM_DATA";
export const RESET_PERSONAL_FORM_DATA = "RESET_PERSONAL_FORM_DATA";
export const SET_SELFIE = "SET_SELFIE";
export const SET_IC_IMG = "SET_IC_IMG";

//Aspirasi
export const SET_MERCHANT_DISTRIBUTOR_LIST = "SET_MERCHANT_DISTRIBUTOR_LIST";
export const SET_MERCHANT_CONTRACT_LISR = "SET_MERCHANT_CONTRACT_LIST";